In [2]:
import sympy
import numpy as np
import isotropic_tensors as it

%load_ext autoreload

# For latex

In [3]:
%autoreload
its = it.IsotropicTensorSystem(usecache=False)

In [4]:
its.tens["I222"].index_representation()

S_{222}(\delta_{ij}\delta_{kl}\delta_{mn})

In [5]:
JtoI = its.symbol_JtoI(get_name=True, index_rep=True)
sd = {JtoI[i][0]:JtoI[i][1:] for i in range(0, len(JtoI))}

for name in "J2", "J22", "J2=2", "J4", "J3-3", "J3---3", "J24", "J2=4":
    print("$%12s$ & $%100s$ & $%20s$\\\\" % (sympy.printing.latex(sd[name][0]), sympy.printing.latex(sd[name][1]), sympy.printing.latex(sympy.Rational(its.otens[name].norm2()).limit_denominator(10**8))))

$       J_{2}$ & $                                                                                  S_{2}(\delta_{ij})$ & $                   3$\\
$      J_{22}$ & $                                                                      S_{22}(\delta_{ij}\delta_{kl})$ & $                   9$\\
$     J_{2=2}$ & $                         - \frac{S_{22}(\delta_{ij}\delta_{kl})}{3} + S_{22}(\delta_{ik}\delta_{jl})$ & $                   5$\\
$       J_{4}$ & $                                                                       S_{4}(\delta_{ij}\delta_{kl})$ & $                   5$\\
$     J_{3-3}$ & $                                                           S_{33}(\delta_{ij}\delta_{kl}\delta_{mn})$ & $        \frac{25}{3}$\\
$J_{3\equiv3}$ & $ - \frac{3 S_{33}(\delta_{ij}\delta_{kl}\delta_{mn})}{5} + S_{33}(\delta_{ik}\delta_{mj}\delta_{ln})$ & $                   7$\\
$      J_{24}$ & $                                                           S_{24}(\delta_{ij}\delta_{kl}\delta_{mn})

In [6]:
JtoI

[('J0', 1, S_{}()),
 ('J2', J_2, S_{2}(\delta_{ij})),
 ('J4', J_4, S_{4}(\delta_{ij}\delta_{kl})),
 ('J6', J_6, S_{6}(\delta_{ij}\delta_{kl}\delta_{mn})),
 ('J8', J_8, S_{8}(\delta_{ij}\delta_{kl}\delta_{mn}\delta_{op})),
 ('J22', J_22, S_{22}(\delta_{ij}\delta_{kl})),
 ('J2=2',
  J_2=2,
  -S_{22}(\delta_{ij}\delta_{kl})/3 + S_{22}(\delta_{ik}\delta_{jl})),
 ('J3-3', J_3-3, S_{33}(\delta_{ij}\delta_{kl}\delta_{mn})),
 ('J3---3',
  J_3\equiv3,
  -3*S_{33}(\delta_{ij}\delta_{kl}\delta_{mn})/5 + S_{33}(\delta_{ik}\delta_{mj}\delta_{ln})),
 ('J42', J_42, S_{42}(\delta_{ij}\delta_{kl}\delta_{mn})),
 ('J4=2',
  J_4=2,
  -S_{42}(\delta_{ij}\delta_{kl}\delta_{mn})/3 + S_{42}(\delta_{ij}\delta_{km}\delta_{ln})),
 ('J24', J_24, S_{24}(\delta_{ij}\delta_{kl}\delta_{mn})),
 ('J2=4',
  J_2=4,
  -S_{24}(\delta_{ij}\delta_{kl}\delta_{mn})/3 + S_{24}(\delta_{ik}\delta_{jl}\delta_{mn})),
 ('J44', J_44, S_{44}(\delta_{ij}\delta_{kl}\delta_{mn}\delta_{op})),
 ('J4=4',
  J_4=4,
  -S_{44}(\delta_{ij}\delta

In [5]:
JtoI

[('J0', 1, 1),
 ('J2', J_2, I_2),
 ('J4', J_4, I_4),
 ('J6', J_6, I_6),
 ('J8', J_8, I_8),
 ('J22', J_22, I_22),
 ('J2=2', J_2=2, -I_22/3 + I_2=2),
 ('J3-3', J_3-3, I_3-3),
 ('J3---3', J_3\equiv3, -3*I_3-3/5 + I_3\equiv3),
 ('J42', J_42, I_42),
 ('J4=2', J_4=2, -I_42/3 + I_4=2),
 ('J24', J_24, I_24),
 ('J2=4', J_2=4, -I_24/3 + I_2=4),
 ('J44', J_44, I_44),
 ('J4=4', J_4=4, -I_44/3 + I_4=4),
 ('J4==4', J_4==4, 3*I_44/35 - 6*I_4=4/7 + I_4==4),
 ('J222', J_222, I_222),
 ('J2=22', J_2=22, -I_222/3 + I_2=22),
 ('J2-2-2-', J_2-2-2-, I_2-2-2- + 2*I_222/9 - I_2=22)]

# Covariance Matrices

In [23]:
its.covariance_matrix((2,), decomposed=True)[0]

Matrix([[sigma0**2*J_22/9 + 2*sigma0**2*J_2=2/15]])

In [24]:
its.covariance_matrix((2,4), decomposed=True)[0]

Matrix([
[ sigma0**2*J_22/9 + 2*sigma0**2*J_2=2/15,                            sigma1**2*J_24/15 + 4*sigma1**2*J_2=4/35],
[sigma1**2*J_42/15 + 4*sigma1**2*J_4=2/35, sigma2**2*J_44/25 + 24*sigma2**2*J_4=4/245 + 8*sigma2**2*J_4==4/315]])

In [22]:
its.covariance_matrix((2,4), decomposed=True)[0]

Matrix([
[ sigma0**2*J_22/9 + 2*sigma0**2*J_2=2/15,                            sigma1**2*J_24/15 + 4*sigma1**2*J_2=4/35],
[sigma1**2*J_42/15 + 4*sigma1**2*J_4=2/35, sigma2**2*J_44/25 + 24*sigma2**2*J_4=4/245 + 8*sigma2**2*J_4==4/315]])

# Inverse Covariance Matrices

In [6]:
CiJ, sigma = its.pseudo_inverse_covariance_matrix((2,))
CiI = CiJ.subs(its.symbol_JtoI()).expand()
CiI
CiJ

Matrix([[J_22/sigma0**2 + 15*J_2=2/(2*sigma0**2)]])

In [7]:
CiJ, sigma = its.pseudo_inverse_covariance_matrix((3,))
CiI = CiJ.subs(its.symbol_JtoI()).expand()
CiI
CiJ

Matrix([[3*J_3-3/sigma1**2 + 35*J_3\equiv3/(2*sigma1**2)]])

In [8]:
CiJ, sigma = its.pseudo_inverse_covariance_matrix((4,))
CiI = CiJ.subs(its.symbol_JtoI()).expand()
CiI
CiJ

Matrix([[J_44/sigma2**2 + 15*J_4=4/(2*sigma2**2) + 315*J_4==4/(8*sigma2**2)]])

In [9]:
CiJ

Matrix([[J_44/sigma2**2 + 15*J_4=4/(2*sigma2**2) + 315*J_4==4/(8*sigma2**2)]])

In [39]:
its.covariance_matrix((2,4))[0]

Matrix([
[ sigma0**2*J_22/9 + 2*sigma0**2*J_2=2/15,                            sigma1**2*J_24/15 + 4*sigma1**2*J_2=4/35],
[sigma1**2*J_42/15 + 4*sigma1**2*J_4=2/35, sigma2**2*J_44/25 + 24*sigma2**2*J_4=4/245 + 8*sigma2**2*J_4==4/315]])

In [48]:
its.covariance_matrix((2,4))[0]

Matrix([
[  sigma0**2*J_22/9 + 2*sigma0**2*J_2=2/15,                           -sigma1**2*J_24/15 - 4*sigma1**2*J_2=4/35],
[-sigma1**2*J_42/15 - 4*sigma1**2*J_4=2/35, sigma2**2*J_44/25 + 24*sigma2**2*J_4=4/245 + 8*sigma2**2*J_4==4/315]])

In [40]:
print(sympy.printing.latex(its.covariance_matrix((2,4))[0]))

\left[\begin{matrix}\frac{\sigma_{0}^{2} J_{22}}{9} + \frac{2 \sigma_{0}^{2} J_{2=2}}{15} & \frac{\sigma_{1}^{2} J_{24}}{15} + \frac{4 \sigma_{1}^{2} J_{2=4}}{35}\\\frac{\sigma_{1}^{2} J_{42}}{15} + \frac{4 \sigma_{1}^{2} J_{4=2}}{35} & \frac{\sigma_{2}^{2} J_{44}}{25} + \frac{24 \sigma_{2}^{2} J_{4=4}}{245} + \frac{8 \sigma_{2}^{2} J_{4==4}}{315}\end{matrix}\right]


In [41]:
print(sympy.printing.latex(its.pseudo_inverse_covariance_matrix((2,4))[0]))

\left[\begin{matrix}\frac{15 \sigma_{2}^{2} J_{2=2}}{2 \sigma_{0}^{2} \sigma_{2}^{2} - 2 \sigma_{1}^{4}} + \frac{\sigma_{2}^{2} J_{22}}{\sigma_{0}^{2} \sigma_{2}^{2} - \sigma_{1}^{4}} & - \frac{15 \sigma_{1}^{2} J_{2=4}}{2 \sigma_{0}^{2} \sigma_{2}^{2} - 2 \sigma_{1}^{4}} - \frac{\sigma_{1}^{2} J_{24}}{\sigma_{0}^{2} \sigma_{2}^{2} - \sigma_{1}^{4}}\\- \frac{15 \sigma_{1}^{2} J_{4=2}}{2 \sigma_{0}^{2} \sigma_{2}^{2} - 2 \sigma_{1}^{4}} - \frac{\sigma_{1}^{2} J_{42}}{\sigma_{0}^{2} \sigma_{2}^{2} - \sigma_{1}^{4}} & \frac{15 \sigma_{0}^{2} J_{4=4}}{2 \sigma_{0}^{2} \sigma_{2}^{2} - 2 \sigma_{1}^{4}} + \frac{\sigma_{0}^{2} J_{44}}{\sigma_{0}^{2} \sigma_{2}^{2} - \sigma_{1}^{4}} + \frac{315 J_{4==4}}{8 \sigma_{2}^{2}}\end{matrix}\right]


In [54]:
%%time
CiJ, sigma = its.pseudo_inverse_covariance_matrix((2,3,4))
#CiI = CiJ.subs(its.symbol_JtoI()).expand()
CiJ

CPU times: user 48 µs, sys: 0 ns, total: 48 µs
Wall time: 56.5 µs


Matrix([
[15*sigma2**2*J_2=2/(2*sigma0**2*sigma2**2 - 2*sigma1**4) + sigma2**2*J_22/(sigma0**2*sigma2**2 - sigma1**4),                                                0,                            15*sigma1**2*J_2=4/(2*sigma0**2*sigma2**2 - 2*sigma1**4) + sigma1**2*J_24/(sigma0**2*sigma2**2 - sigma1**4)],
[                                                                                                          0, -3*J_3-3/sigma1**2 - 35*J_3\equiv3/(2*sigma1**2),                                                                                                                                      0],
[15*sigma1**2*J_4=2/(2*sigma0**2*sigma2**2 - 2*sigma1**4) + sigma1**2*J_42/(sigma0**2*sigma2**2 - sigma1**4),                                                0, 15*sigma0**2*J_4=4/(2*sigma0**2*sigma2**2 - 2*sigma1**4) + sigma0**2*J_44/(sigma0**2*sigma2**2 - sigma1**4) + 315*J_4==4/(8*sigma2**2)]])

In [53]:
sympy.srepr(its.pseudo_inverse_covariance_matrix((2,3,4), full_output=True))

"(MutableDenseMatrix([[Add(Mul(Integer(15), Pow(Symbol('sigma2', real=True, positive=True), Integer(2)), Pow(Add(Mul(Integer(2), Pow(Symbol('sigma0', real=True, positive=True), Integer(2)), Pow(Symbol('sigma2', real=True, positive=True), Integer(2))), Mul(Integer(-1), Integer(2), Pow(Symbol('sigma1', real=True, positive=True), Integer(4)))), Integer(-1)), Symbol('J_2=2', commutative=False)), Mul(Pow(Symbol('sigma2', real=True, positive=True), Integer(2)), Pow(Add(Mul(Pow(Symbol('sigma0', real=True, positive=True), Integer(2)), Pow(Symbol('sigma2', real=True, positive=True), Integer(2))), Mul(Integer(-1), Pow(Symbol('sigma1', real=True, positive=True), Integer(4)))), Integer(-1)), Symbol('J_22', commutative=False))), Integer(0), Add(Mul(Integer(15), Pow(Symbol('sigma1', real=True, positive=True), Integer(2)), Pow(Add(Mul(Integer(2), Pow(Symbol('sigma0', real=True, positive=True), Integer(2)), Pow(Symbol('sigma2', real=True, positive=True), Integer(2))), Mul(Integer(-1), Integer(2), Pow(

In [31]:
print(sympy.printing.latex(its.x))

\left[\begin{matrix}T\\R\\S\end{matrix}\right]


In [55]:
print(sympy.printing.latex(CiJ))

\left[\begin{matrix}\frac{15 \sigma_{2}^{2} J_{2=2}}{2 \sigma_{0}^{2} \sigma_{2}^{2} - 2 \sigma_{1}^{4}} + \frac{\sigma_{2}^{2} J_{22}}{\sigma_{0}^{2} \sigma_{2}^{2} - \sigma_{1}^{4}} & 0 & \frac{15 \sigma_{1}^{2} J_{2=4}}{2 \sigma_{0}^{2} \sigma_{2}^{2} - 2 \sigma_{1}^{4}} + \frac{\sigma_{1}^{2} J_{24}}{\sigma_{0}^{2} \sigma_{2}^{2} - \sigma_{1}^{4}}\\0 & - \frac{3 J_{3-3}}{\sigma_{1}^{2}} - \frac{35 J_{3\equiv3}}{2 \sigma_{1}^{2}} & 0\\\frac{15 \sigma_{1}^{2} J_{4=2}}{2 \sigma_{0}^{2} \sigma_{2}^{2} - 2 \sigma_{1}^{4}} + \frac{\sigma_{1}^{2} J_{42}}{\sigma_{0}^{2} \sigma_{2}^{2} - \sigma_{1}^{4}} & 0 & \frac{15 \sigma_{0}^{2} J_{4=4}}{2 \sigma_{0}^{2} \sigma_{2}^{2} - 2 \sigma_{1}^{4}} + \frac{\sigma_{0}^{2} J_{44}}{\sigma_{0}^{2} \sigma_{2}^{2} - \sigma_{1}^{4}} + \frac{315 J_{4==4}}{8 \sigma_{2}^{2}}\end{matrix}\right]


# Infer Symbol Algebra

In [11]:
sympy.Matrix(its.symbol_algebra(product=2)).T

Matrix([
[J_2**2, J_2*J_22, J_2*J_24, J_2*J_222, J_2*J_2=22, J_22**2, J_22*J_24, J_22*J_222, J_22*J_2=22, J_2=2**2, J_2=2*J_2=4, J_2=2*J_2=22, J_2=2*J_2-2-2-, J_42*J_24, J_4=2*J_2=4],
[     3,    3*J_2,    3*J_4,    3*J_22,      J_2=2,  3*J_22,    3*J_24,    3*J_222,      J_2=22,    J_2=2,       J_2=4,   2*J_2=22/3,       J_2-2-2-,    3*J_44,       J_4=4]])

In [12]:
sympy.Matrix(its.symbol_algebra(product=3)).T

Matrix([
[ J_3-3**2, J_3\equiv3**2],
[5*J_3-3/3,    J_3\equiv3]])

In [13]:
sympy.Matrix(its.symbol_algebra(product=4)).T

Matrix([
[J_4**2, J_4*J_42, J_4*J_44, J_24*J_44, J_2=4*J_4=4, J_44**2,  J_4=4**2, J_4==4**2],
[     5,    5*J_2,    5*J_4,    5*J_24,   7*J_2=4/6,  5*J_44, 7*J_4=4/6,    J_4==4]])

# Basis relations

In [14]:
sympy.Matrix(its.symbol_JtoI())

Matrix([
[         1,                              1],
[       J_2,                            I_2],
[       J_4,                            I_4],
[       J_6,                            I_6],
[       J_8,                            I_8],
[      J_22,                           I_22],
[     J_2=2,                -I_22/3 + I_2=2],
[     J_3-3,                          I_3-3],
[J_3\equiv3,        -3*I_3-3/5 + I_3\equiv3],
[      J_42,                           I_42],
[     J_4=2,                -I_42/3 + I_4=2],
[      J_24,                           I_24],
[     J_2=4,                -I_24/3 + I_2=4],
[      J_44,                           I_44],
[     J_4=4,                -I_44/3 + I_4=4],
[    J_4==4, 3*I_44/35 - 6*I_4=4/7 + I_4==4],
[     J_222,                          I_222],
[    J_2=22,              -I_222/3 + I_2=22],
[  J_2-2-2-,  I_2-2-2- + 2*I_222/9 - I_2=22]])

In [15]:
sympy.Matrix(its.symbol_ItoJ())

Matrix([
[         1,                           1],
[       I_2,                         J_2],
[       I_4,                         J_4],
[       I_6,                         J_6],
[       I_8,                         J_8],
[      I_22,                        J_22],
[     I_2=2,              J_22/3 + J_2=2],
[     I_3-3,                       J_3-3],
[I_3\equiv3,      3*J_3-3/5 + J_3\equiv3],
[      I_42,                        J_42],
[     I_4=2,              J_42/3 + J_4=2],
[      I_24,                        J_24],
[     I_2=4,              J_24/3 + J_2=4],
[      I_44,                        J_44],
[     I_4=4,              J_44/3 + J_4=4],
[    I_4==4, J_44/5 + 6*J_4=4/7 + J_4==4],
[     I_222,                       J_222],
[    I_2=22,            J_222/3 + J_2=22],
[  I_2-2-2-, J_2-2-2- + J_222/9 + J_2=22]])

# Determinants

In [12]:
A = its("I2=2").numeric_rep.reshape(9,9)
np.linalg.eigvalsh(A)

array([0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [39]:
A = its("J2=2").numeric_rep.reshape(9,9)
np.linalg.eigvalsh(A)

array([-7.74573024e-17,  0.00000000e+00,  7.80333789e-17,  1.74600905e-16,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00])

In [16]:
A = its("I22").numeric_rep.reshape(9,9)
print(np.round(np.linalg.eigvalsh(A), 10))

[-0. -0.  0.  0.  0.  0.  0.  0.  3.]


In [20]:
a, b = 1., 1.
M = a*its("J22").numeric_rep + b*its("J2=2").numeric_rep
print(np.round(np.linalg.eigvalsh(M.reshape(9,9)), 10))

[-0.  0.  0.  1.  1.  1.  1.  1.  3.]


In [26]:
a, b = 3., 1.
M = a*its("J22").numeric_rep + b*its("J2=2").numeric_rep
eig = np.round(np.linalg.eigvalsh(M.reshape(9,9)), 10)
print(np.prod(eig[np.abs(eig) >= 1e-10]))

9.0


In [38]:
a, b = 5./9., 2./3.
M = a*its("J22").numeric_rep + b*its("J2=2").numeric_rep
eig = np.linalg.eigvalsh(M.reshape(9,9))
print(np.round(eig, 10), np.prod(eig[np.abs(eig) >= 1e-10]), 1./(b**5*a*3))

[-0.          0.          0.          0.66666667  0.66666667  0.66666667
  0.66666667  0.66666667  1.66666667] 0.21947873799725656 4.556250000000001


In [37]:
a, b = 5./9., 2./3.
M = its("J4").numeric_rep
eig = np.linalg.eigvalsh(M.reshape(9,9))
print(np.round(eig, 10), np.prod(eig[np.abs(eig) >= 1e-10]), b**5*a*3)

[-0.         -0.          0.          0.66666667  0.66666667  0.66666667
  0.66666667  0.66666667  1.66666667] 0.2194787379972567 0.21947873799725645


In [32]:
a, b = 1./5., 3./2.
M = a*its("J22").numeric_rep + b*its("J2=2").numeric_rep
eig = np.linalg.eigvalsh(M.reshape(9,9))
print(np.round(eig, 10), np.prod(eig[np.abs(eig) >= 1e-10]), 1./np.prod(eig[np.abs(eig) >= 1e-10]), b**5*3*a, 1./(b**5*3*a))

[-0.   0.   0.   0.6  1.5  1.5  1.5  1.5  1.5] 4.556249999999997 0.21947873799725667 4.55625 0.2194787379972565


In [34]:
a, b = 3., -2.
M = a*its("J22").numeric_rep + b*its("J2=2").numeric_rep
eig = np.linalg.eigvalsh(M.reshape(9,9))
print(np.round(eig, 10), np.prod(eig[np.abs(eig) >= 1e-10]), 1./np.prod(eig[np.abs(eig) >= 1e-10]), b**5*3*a, 1./(b**5*3*a))

[-2. -2. -2. -2. -2. -0. -0.  0.  9.] -288.0000000000005 -0.003472222222222216 -288.0 -0.003472222222222222
